module.exports = {
'auto': 'sozinhus',
'baseline': 'linhaBasis',
'bold': 'escurus',
'bolder': 'maisEscurus',
'condensed': 'condensadis',
'cursive': 'cursivis',
'dashed': 'tracejadis',
'dotted': 'pontilhadis',
'double': 'duplis',
'expanded': 'expandidis',
'extra-condensed': 'extraCondensadis',
'extra-expanded':  'extraExpandidis',
'fixed': 'paradis',
'inset': 'inserizis',
'hidden': 'escondidis',
'italic': 'inclinadis',
'large':  'grandis',
'smaller':'menorzis',
'larger' : 'maiorzis',
'length': 'comprimentius',
'light' :'levis',
'medium': 'mediuzis',
'none': 'nenhumzis',
'normal' : 'normalzis',
'no-repeat': 'naoRepetizis',
'oblique': 'obliquazis',
'outset': 'comecius',
'repeat': 'repetizis',
'repeat-x': 'repetirzisX',
'repeat-y': 'repetirzisY',
'sans-serif': 'semSerifis',
'scrool': 'tambadis',
'serif': 'serifadis',
'shape': 'formis',
'small': 'pequenis',
'semi-condensed': 'semiCondensadis',
'semi-expanded': 'semiExpandidis',
'solid': 'solidis',
'transparent': 'transparentis',
'ultra-condensed': 'ultraCondensadis',
'ultra-expanded': 'ultraExpandidis',
'visible': 'visivis',
'x-large' : 'extraGrandis',
'xx-large': 'ultraGrandis',
'x-small': 'extraPequenis',
'xx-small': 'ultraPequenis'
}
