module.exports = {
'auto': 'sozinhus',
'baseline': 'linha-di-basis',
'bold': 'escurus',
'bolder': 'mais-iscurus',
'condensed': 'condensadis',
'cursive': 'cursivis',
'dashed': 'tracejadis',
'dotted': 'pontilhadis',
'double': 'duplis',
'expanded': 'expandidis',
'extra-condensed': 'extra-condensadis',
'extra-expanded':  'extra-expandidis',
'fixed': 'paradis',
'inset': 'inserizis',
'hidden': 'escondidis',
'italic': 'inclinadis',
'large':  'grandis',
'smaller':'menorzis',
'larger' : 'maiorzis',
'length': 'comprimentius',
'light' :'levis',
'medium': 'mediuzis',
'none': 'nenhumzis',
'normal' : 'normalzis',
'no-repeat': 'nao-repetizis',
'oblique': 'obliquazis',
'outset': 'comecius',
'repeat': 'repetizis',
'repeat-x': 'repetirzis-x',
'repeat-y': 'repetirzis-y',
'sans-serif': 'sem-serifis',
'scrool': 'tambadis',
'serif': 'serifadis',
'shape': 'formis',
'small': 'pequenis',
'semi-condensed': 'semi-condensadis',
'semi-expanded': 'semi-expandidis',
'solid': 'solidis',
'transparent': 'transparentis',
'ultra-condensed': 'ultra-condensadis',
'ultra-expanded': 'ultra-expandidis',
'visible': 'visivis',
'x-large' : 'extra-grandis',
'xx-large': 'ultra-grandis',
'x-small': 'extra-pequenis',
'xx-small': 'ultra-pequenis'
}
